use_frameworks!

target 'YYNative_Example' do
  pod 'YYNative', :path => '../'
	pod 'ZLPhotoBrowser'
  target 'YYNative_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
